//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHopDong
    {
        public string SoHopDong { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual HopDong HopDong { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
